ServerRoot "/usr"
ServerName localhost
Listen 127.0.0.1:8080

PidFile "/tmp/estudioclaro-httpd.pid"
Mutex file:/tmp
ErrorLog "/Users/macbookprom4pro/Desktop/Reto2_EstudioClaro/logs/error.log"
CustomLog "/Users/macbookprom4pro/Desktop/Reto2_EstudioClaro/logs/access.log" common

LoadModule mpm_prefork_module libexec/apache2/mod_mpm_prefork.so
LoadModule authn_core_module libexec/apache2/mod_authn_core.so
LoadModule authz_core_module libexec/apache2/mod_authz_core.so
LoadModule authz_host_module libexec/apache2/mod_authz_host.so
LoadModule mime_module libexec/apache2/mod_mime.so
LoadModule log_config_module libexec/apache2/mod_log_config.so
LoadModule dir_module libexec/apache2/mod_dir.so
LoadModule alias_module libexec/apache2/mod_alias.so
LoadModule unixd_module libexec/apache2/mod_unixd.so

TypesConfig /private/etc/apache2/mime.types
AddType text/css .css
AddType application/javascript .js
DirectoryIndex index.html

DocumentRoot "/Users/macbookprom4pro/Desktop/Reto2_EstudioClaro/vacio"

<Directory "/Users/macbookprom4pro/Desktop/Reto2_EstudioClaro/vacio">
    Require all granted
</Directory>

<VirtualHost 127.0.0.1:8080>
    ServerName localhost
    Alias /tuapp "/Users/macbookprom4pro/Desktop/Reto2_EstudioClaro/app"
    <Directory "/Users/macbookprom4pro/Desktop/Reto2_EstudioClaro/app">
        Options FollowSymLinks
        AllowOverride None
        Require all granted
        DirectoryIndex index.html
    </Directory>
</VirtualHost>
